#!/usr/bin/env bash
#
# Repository invariants that formatters and linters do not cover. Each one
# guards a failure mode that is either silent (the change merges green having
# deployed nothing) or unrecoverable (a secret reaches the history).
#
# Run over the staged files pre-commit passes in, or over everything tracked
# when called with no arguments. Kept POSIX-ish so it runs on the bash 3.2
# that ships with macOS as well as on the runner.
set -uo pipefail

cd "$(git rev-parse --show-toplevel)" || exit 1

if [ "$#" -gt 0 ]; then
  files=$(printf '%s\n' "$@")
else
  files=$(git ls-files)
fi

status=0

fail() {
  status=1
  printf '%s\n' "$@" >&2
}

while IFS= read -r f; do
  [ -n "$f" ] || continue

  case "$f" in
    live/*/backend.tf | live/*/providers.tf | live/*/context.tf)
      fail "$f: generated by root.hcl at run time and excluded by .gitignore." \
        "  It holds the resolved tenant and subscription ids. Unstage it:" \
        "    git rm --cached '$f'"
      ;;
  esac

  case "$f" in
    *.tfstate | *.tfstate.backup)
      fail "$f: Terraform state. State lives in the Azure backend and can hold" \
        "  secrets in plain text. Unstage it: git rm --cached '$f'"
      ;;
  esac

  case "$f" in
    live/*/terragrunt.stack.hcl)
      fail "$f: stack leaves are not used in this repository." \
        "  A stack leaf has no terragrunt.hcl, so discovery skips it: the PR" \
        "  plans nothing, every gate passes with nothing to gate, and it merges" \
        "  green having deployed nothing. Write a unit with a terragrunt.hcl."
      ;;
  esac
done <<EOF
$files
EOF

# A directory under live/ holding Terraform but no terragrunt.hcl is invisible
# to discovery, and fails the same silent way as a stack leaf. A unit without a
# committed lock file resolves its providers afresh on every run, so plan and
# apply can use different versions.
while IFS= read -r dir; do
  [ -n "$dir" ] || continue
  [ -f "$dir/terragrunt.hcl" ] || fail \
    "$dir: has Terraform but no terragrunt.hcl, so it is not a unit." \
    "  Discovery skips it entirely and nothing is ever planned or applied."
  [ -f "$dir/.terraform.lock.hcl" ] || fail \
    "$dir: no .terraform.lock.hcl, so provider versions float between runs" \
    "  and the plan you review can differ from what applies. Generate one:" \
    "    terragrunt --working-dir $dir init -backend=false"
done <<EOF
$(git ls-files 'live/*.tf' | sed 's|/[^/]*$||' | sort -u)
EOF

exit $status
